### ISSUE TITLE
【报错】图片配置有错

### ISSUE THREAD

**Issue by Agnes4m** [jcjrobert/nonebot-plugin-random#1]
python3.9.15
在bot.py所在文件夹下，`data/random`下（这个目录没有创建，手动创建的）新建文件夹，放入图片和config.json
![image](https://user-images.githubusercontent.com/70925546/197977031-1980243b-4242-4f16-8c18-09c08e42e1e0.png)
![image](https://user-images.githubusercontent.com/70925546/197977711-afc43e2c-5bc8-4e9a-91a7-72b3585c1418.png)

**Comment by jcjrobert** [comment]
请问config.json具体内容是什么呢，如果你只是想要个/随机龙图的话，可以不用配置，把config.json删掉

**Comment by Agnes4m** [comment]
去掉的情况下也是这个报错，我本以为需要个空文件在这里，但也没有解决问题

**Comment by jcjrobert** [comment]
我发现问题了，等我发新版，但是现在没空（x）
现在暂行方案的话，你需要自己配置config.json下的"message"
没配置的话，默认不会响应
但是出现图中那个报错那就是说明你json文件本身格式是有错误的

**Comment by jcjrobert** [comment]
插件已更新，如问题还未解决或还有其他问题欢迎提出

**Comment by Agnes4m** [comment]
没问题了谢谢大佬

**Comment by llllin2333** [comment]
请问想随机语音配置文件该怎么写，萌新实在不知道改写str=还是type=，自己写的是错的
可以的话能给个参考吗，谢谢大佬(灬ꈍ ꈍ灬)

**Comment by Agnes4m** [comment]
之前配置config.json，没记错应该是这么写的，是报错的。
现在有问题，比如我想让两个命令都能响应，例如这个可以用`随机龙图`，也能用`今日龙图`，该如何设置？
```
"draw_output"="image"
"draw_mode"="direct"
"message_type"="command"
"message"=["随机龙图"]
"is_tome"=false
```

**Comment by jcjrobert** [comment]
"message": ["随机龙图","今日龙图"]
注意json格式，你可以去sojson.com查看格式是否正确

**Comment by Agnes4m** [comment]
报错
![image](https://user-images.githubusercontent.com/70925546/200117086-4e5f78ae-854b-47b3-950f-3a841d17a012.png)
![image](https://user-images.githubusercontent.com/70925546/200117106-7d03b4c4-7b32-4618-8040-5b390201eac0.png)

**Comment by jcjrobert** [comment]
> 报错 ![image](https://user-images.githubusercontent.com/70925546/200117086-4e5f78ae-854b-47b3-950f-3a841d17a012.png) ![image](https://user-images.githubusercontent.com/70925546/200117106-7d03b4c4-7b32-4618-8040-5b390201eac0.png)

你这就不是json文件的格式（恼）
看看我上条回复
=换成:
然后整体用{}包上
除了最后一句后面应有,号

```
{
"draw_output":"image",
"draw_mode":"direct",
"message_type":"command",
"message":["随机猫猫"],
"is_tome":false
}
```

**Comment by Agnes4m** [comment]
感谢大佬，是我没看到呜呜呜
