### ISSUE TITLE
当前文件夹 下没有文件，请放置任意文件并配置好后再使用命令

### ISSUE THREAD

**Issue by Nenot233** [jcjrobert/nonebot-plugin-random#4]
![image](https://user-images.githubusercontent.com/108965579/204095312-a50848e1-be71-4542-8c8f-14e6f6fa09f6.png)
PY3.9
NB2RC1

**Comment by Nenot233** [comment]
未配置config.json

**Comment by Nenot233** [comment]
{
  "draw_output": "record",
  "message_type": "command",
  "message": [
    "听听主任",
    "听听hoshimi",
    "听听Hoshimi"
  ],
  "is_tome": false
}
![image](https://user-images.githubusercontent.com/108965579/204095883-6bbfc81e-9a1c-4d7f-a454-1b69dbd8aecd.png)
![image](https://user-images.githubusercontent.com/108965579/204095972-5904387b-871d-473b-bcea-9f148ce41da2.png)
这个地方我配置哪有问题呢？

**Comment by jcjrobert** [comment]
未配置默认是抽图片，肯定不行的
下面这个配置没问题，截图报错不要单截这句话，上面才是重点
看起来是文件有问题？你加下群发个文件看看
我复现不了

**Comment by jcjrobert** [comment]
已确认是windows下读取文件默认是gbk编码
将在后续版本更新中强制使用utf-8编码读取json文件，感谢反馈

**Comment by jcjrobert** [comment]
已修复，请将插件更新至最新版本
